# Generated by Django 4.2.1 on 2023-05-20 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='script',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='psc.playscript'),
        ),
        migrations.AddField(
            model_name='scene',
            name='script',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='psc.playscript'),
        ),
    ]
